version: '3.9'

services:

  db:
    image: 'postgres'
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server: 
    build: .
    # image: jaredtwe/server-server:latest # Changed from 'build: .' to using the image from Docker Hub. Must switch to 'build: .' making changes to the server code.
    ports:
      - "8081:8080" #outsideworld:containerworld
    depends_on:
      db:
        condition: service_healthy
  # The next lines do not work because I could not figure out how to get my Angular `ng build --prod` from just showing a white screen, despite `ng serve -o` working fine.
  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server